# Generated by Django 6.0 on 2025-12-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('TRANSFER_REQUEST', 'Transfer Request'), ('TRANSFER_APPROVED', 'Transfer Approved'), ('TRANSFER_REJECTED', 'Transfer Rejected')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('DISMISSED', 'Dismissed')], default='UNREAD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.branch')),
                ('stock_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.stockmovement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
