# Generated by Django 6.0 on 2025-12-10 20:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transferalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='weighted_avg_purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='BrokenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('damage_type', models.CharField(choices=[('BROKEN', 'Broken'), ('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective'), ('LOST', 'Lost'), ('STOLEN', 'Stolen'), ('OTHER', 'Other')], max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit when purchased', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broken_items', to='core.stock')),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyProfitAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('total_quantity_sold', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('weighted_avg_purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('broken_quantity', models.IntegerField(default=0)),
                ('broken_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('allocated_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('opening_stock', models.IntegerField(default=0)),
                ('closing_stock', models.IntegerField(default=0)),
                ('stock_turnover_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'ordering': ['-month', 'branch', 'product'],
                'unique_together': {('branch', 'product', 'month')},
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit_purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.stock')),
            ],
            options={
                'ordering': ['received_date'],
            },
        ),
        migrations.DeleteModel(
            name='TransferAlert',
        ),
    ]
