# Generated by Django 6.0 on 2025-12-11 03:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stock_weighted_avg_purchase_price_brokenproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULLY_FULFILLED', 'Fully Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('total_items_ordered', models.IntegerField(default=0, help_text='Total items in the order')),
                ('total_items_fulfilled', models.IntegerField(default=0, help_text='Total items delivered so far')),
                ('total_items_remaining', models.IntegerField(default=0, help_text='Items still to be delivered')),
                ('total_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total payments collected', max_digits=12)),
                ('total_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding balance', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_fulfillments', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='core.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_capacity', models.IntegerField(default=0, help_text='Maximum items this vehicle can carry')),
                ('items_loaded', models.IntegerField(default=0, help_text='Actual items loaded in this shipment')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LOADING', 'Loading'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('PARTIALLY_DELIVERED', 'Partially Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=30)),
                ('scheduled_date', models.DateTimeField()),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.TextField()),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_signature', models.BooleanField(default=False, help_text='Customer signed for delivery')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_created', to='core.employee')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_shipments_driven', to='core.employee')),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.orderfulfillment')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_shipments', to='core.trip')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_shipments', to='core.vehicle')),
            ],
            options={
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True)),
                ('amount_collected', models.DecimalField(decimal_places=2, help_text='Amount collected in this payment', max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Cheque'), ('CARD', 'Credit/Debit Card'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_date', models.DateTimeField()),
                ('deposit_date', models.DateTimeField(blank=True, help_text='When was money deposited to branch', null=True)),
                ('is_deposited', models.BooleanField(default=False, help_text='Has this payment been deposited to a branch?')),
                ('reference_number', models.CharField(blank=True, help_text='Transaction ID, cheque number, etc.', max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_collections', to='core.branch')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_collected', to='core.employee')),
                ('deposited_to_branch', models.ForeignKey(blank=True, help_text='Which branch received this money', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_received', to='core.branch')),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.orderfulfillment')),
                ('shipment', models.ForeignKey(blank=True, help_text='Payment collected during this shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.ordershipment')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField(help_text='Original quantity ordered')),
                ('quantity_delivered', models.IntegerField(help_text='Quantity delivered in this shipment')),
                ('quantity_remaining', models.IntegerField(help_text='Quantity still to be delivered')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_deliveries', to='core.orderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.ordershipment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
