# Generated by Django 6.0 on 2025-12-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_businessnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessnote',
            options={'ordering': ['page_number']},
        ),
        migrations.RemoveField(
            model_name='businessnote',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='businessnote',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='businessnote',
            name='title',
        ),
        migrations.AddField(
            model_name='businessnote',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='businessnote',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
