# Generated by Django 6.0 on 2025-12-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_airtable_fields'),
        ('core', '0008_alter_businessnote_options_and_more'),
    ]

    operations = [
    ]
