# Generated by Django 4.2.7 on 2025-12-21 07:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20251218_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='completion_branch',
            field=models.ForeignKey(blank=True, help_text='Branch where item was completed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_completed',
            field=models.IntegerField(default=0, help_text='Quantity completed so far'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_ordered',
            field=models.IntegerField(default=1, help_text='Original quantity ordered'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_remaining',
            field=models.IntegerField(default=0, help_text='Quantity still pending'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_COMPLETED', 'Partially Completed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PARTIALLY_COMPLETED', 'Partially Completed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('new_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_order_changes', to='core.branch')),
                ('old_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_order_changes', to='core.branch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.order')),
            ],
            options={
                'ordering': ['-change_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_completed', models.IntegerField(help_text='Quantity completed in this action')),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('completion_branch', models.ForeignKey(help_text='Branch where completion happened', on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.orderitem')),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
    ]
