# Generated by Django 4.2.7 on 2025-12-28 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_add_inventory_layer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='airtable_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='airtable_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='airtable_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='airtable_id',
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational Expense'), ('SALE_RELATED', 'Sale Related Expense'), ('TRANSPORT', 'Transport/Delivery'), ('UTILITIES', 'Utilities'), ('SALARY', 'Salary'), ('RENT', 'Rent'), ('MAINTENANCE', 'Maintenance'), ('DELIVERY', 'Delivery Charges'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalStockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_number', models.CharField(max_length=50, unique=True)),
                ('system_quantity', models.IntegerField(help_text='Quantity according to system')),
                ('physical_quantity', models.IntegerField(help_text='Actual physical count')),
                ('discrepancy', models.IntegerField(help_text='Difference (physical - system)')),
                ('discrepancy_value', models.DecimalField(decimal_places=2, help_text='Value of discrepancy', max_digits=10)),
                ('count_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='core.branch')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'ordering': ['-count_date'],
            },
        ),
    ]
