# Generated by Django 4.2.7 on 2026-02-08 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_allowanceregister_chartofaccount_ledgertransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalledgertransaction',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.branch'),
        ),
        migrations.AddField(
            model_name='historicalledgertransaction',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.vehicle'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transactions', to='core.branch'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transactions', to='core.vehicle'),
        ),
    ]
