# Generated by Django 4.2.7 on 2026-02-10 16:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_saleitem_decimal_broken'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS core_physicalstockcount (
                id BIGSERIAL PRIMARY KEY,
                count_number VARCHAR(50) UNIQUE NOT NULL,
                branch_id BIGINT NOT NULL REFERENCES core_branch(id) ON DELETE CASCADE,
                product_id BIGINT NOT NULL REFERENCES core_product(id) ON DELETE CASCADE,
                system_quantity NUMERIC(12,2) NOT NULL,
                physical_quantity NUMERIC(12,2) NOT NULL,
                discrepancy NUMERIC(12,2) NOT NULL,
                discrepancy_value NUMERIC(10,2) NOT NULL,
                count_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                counted_by_id BIGINT NULL REFERENCES core_employee(id) ON DELETE SET NULL,
                notes TEXT NOT NULL DEFAULT ''
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='brokenproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorylayer',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorylayer',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlyprofitanalysis',
            name='broken_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlyprofitanalysis',
            name='closing_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlyprofitanalysis',
            name='opening_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlyprofitanalysis',
            name='total_quantity_sold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderfulfillment',
            name='total_items_fulfilled',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total items delivered so far', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderfulfillment',
            name='total_items_ordered',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total items in the order', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderfulfillment',
            name='total_items_remaining',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Items still to be delivered', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_completed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity completed so far', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_ordered',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Original quantity ordered', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_remaining',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity still pending', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitemcompletion',
            name='quantity_completed',
            field=models.DecimalField(decimal_places=2, help_text='Quantity completed in this action', max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='items_loaded',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual items loaded in this shipment', max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='vehicle_capacity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum items this vehicle can carry', max_digits=12),
        ),
        migrations.AlterField(
            model_name='physicalstockcount',
            name='discrepancy',
            field=models.DecimalField(decimal_places=2, help_text='Difference (physical - system)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='physicalstockcount',
            name='physical_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Actual physical count', max_digits=12),
        ),
        migrations.AlterField(
            model_name='physicalstockcount',
            name='system_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity according to system', max_digits=12),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity_delivered',
            field=models.DecimalField(decimal_places=2, help_text='Quantity delivered in this shipment', max_digits=12),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity_ordered',
            field=models.DecimalField(decimal_places=2, help_text='Original quantity ordered', max_digits=12),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity_remaining',
            field=models.DecimalField(decimal_places=2, help_text='Quantity still to be delivered', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='min_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
